schema_version: 20180708
name: simpleflow
version: 0.0.18
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk9-1.0.70
run_image: fnproject/fn-java-fdk:jdk9-1.0.70
cmd: com.example.fn.HelloFunction::handleRequest
format: http
triggers:
- name: simpleflow
  type: http
  source: /simpleflow
