schema_version: 20180708
name: simpleflow
version: 0.0.3
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.85
run_image: fnproject/fn-java-fdk:jre11-1.0.85
cmd: com.fn.FlowFunction::handleDouble
format: http-stream
triggers:
- name: simpleflow
  type: http
  source: /simpleflow
